[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F -R
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm-error.log
user=root

[program:laravel-queue]
command=php /var/www/html/artisan queue:work redis --sleep=3 --tries=3
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr